name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'ProyectoComponentesMarketplace'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ac8b6b9d482541d38242847a0199ffbd }}
        package: '${{ github.workspace }}/target/*.war'